export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="spaceship"

plugins=(
  autojump
  git
  osx
  rbenv
  zsh-syntax-highlighting
  zsh-autosuggestions
)

SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_DIR_COLOR=yellow
SPACESHIP_GIT_BRANCH_COLOR=cyan
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_NODE_SHOW=false
SPACESHIP_RUBY_SHOW=false
SPACESHIP_DOCKER_SHOW=false

source $ZSH/oh-my-zsh.sh

source "$HOME/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
