# load our oh-my-zsh completion functions (https://github.com/zsh-users/zsh-completions)
fpath=(~/.config/zsh/completions/src $fpath)

# completion
autoload -U compinit && compinit

# load custom executable functions
for function in ~/.dotfiles/zsh/functions/*; do
  source $function
done

# makes color constants available
autoload -U colors
colors

# enable colored output from ls, etc
export CLICOLOR=1

# history settings
setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.zhistory
HISTSIZE=4096
SAVEHIST=4096

# awesome cd movements from zshkit
setopt autocd autopushd pushdminus pushdsilent pushdtohome cdablevars
DIRSTACKSIZE=5

# Enable extended globbing
setopt extendedglob

# Allow [ or ] whereever you want
unsetopt nomatch

# vi mode
bindkey -v
bindkey "^F" vi-cmd-mode
bindkey jj vi-cmd-mode

# handy keybindings
bindkey "^B" beginning-of-line
bindkey "^E" end-of-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey "^F" forward-word
bindkey "^D" backward-word
bindkey -s "^T" "^[Isudo ^[A" # "t" for "toughguy"

# use nvim as the visual editor
export VISUAL=nvim
export EDITOR=$VISUAL

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - --no-rehash)"

# load zsh git prompt
# TODO: Use oh-my-zsh framework
source ~/.dotfiles/zsh/git-prompt/git-prompt.plugin.zsh
ZSH_THEME_GIT_PROMPT_PREFIX="( "
ZSH_THEME_GIT_PROMPT_SUFFIX=" )"
ZSH_THEME_GIT_PROMPT_SEPARATOR=" | "
ZSH_THEME_GIT_PROMPT_CHANGED="%{$fg[cyan]%}✚"
PROMPT='%{$fg_bold[yellow]%}%m%~%b$(git_super_status) %# '

# XDG Base Directory Specification
XDG_CONFIG_HOME=$HOME/.config

# Elixir path
export PATH="$PATH:/usr/local/Cellar/elixir/1.0.5/bin"

# mkdir .git/safe in the root of repositories you trust
export PATH=".git/safe/../../bin:$PATH"

export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"

# gh
eval "$(gh alias -s)"

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# env variables
[[ -f ~/.env ]] && source ~/.env

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
